### ISSUE TITLE
TinyLFU?

### ISSUE THREAD

**Issue by ben-manes** [nanites/In-Network-Hadoop-NDN-CacheSimulator#2]
Hi!

I was happily surprised to see that you adapted policies from my [cache simulator](https://github.com/ben-manes/caffeine/wiki/Simulator) for your research. Hopefully its been helpful.

My evaluation led to adopting TinyLFU after making some modifications. I found it often performed as well as or better than LIRS, but is far simpler to implement and make efficient. Implementing LIRS from the papers and original C code is more reverse engineering than understanding, though it does extremely well. I've been very happy with TinyLFU and contributed towards a longer paper, so I would find it interesting to see how it does in your analysis.

Also, when appropriate please send me your paper / results.

Cheers,
Ben

**Comment by eric135** [comment]
Ben,

Thanks for taking a look at our project. We found your policy implementations to be quite helpful indeed!

The results of our evaluations with this simulator will actually appear later this month in ACM ICN 2019 ("On the Power of In-Network Caching in the Hadoop Distributed File System" - a link to the paper from the conference website should hopefully appear in the near future). We didn't get a chance to integrate TinyLFU into the simulator in time for the paper, but it would definitely be an excellent addition to this simulator and an interesting avenue for future work, particularly if it often performs better than LIRS!

Eric

**Comment by ben-manes** [comment]
Thanks Eric, I'll keep an eye out for the paper!
